name: 'UpdateData'

on:
  #push:
  schedule:
    - cron: '30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Say Hello
      run: echo Hi!
    - name: Run a shell file
      run: bash ./update.sh
